version: "3.10"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=contest
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=contestadmin

  backend:
    build: ./wordscontest
    command: /bin/sh -c "entrypoint.sh"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=contest
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=contestadmin
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

