version: "3.10"

services:
  db:
    image: postgres
    volumes:
      - ./wordscontest/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=contest
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=contestadmin

  backend:
    build: ./wordscontest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=contest
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=contestadmin
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

